#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
YOLOv8 训练脚本 - 智能图像标注与推理系统
功能：
  1. 自动检测数据集结构（扁平目录 / YOLO标准目录）
  2. 自动划分训练集/验证集 (默认8:2)
  3. 支持自定义类别名称
  4. 支持batch size / epochs 配置
  5. 模型保存到固定输出目录（--output参数）
"""

import os
import sys
import random
import shutil
import argparse
import time
from datetime import datetime

from ultralytics import YOLO

# ================= 参数解析 =================
parser = argparse.ArgumentParser(description="YOLOv8 训练脚本")
parser.add_argument('--dataset', type=str, required=True, help='数据集目录路径')
parser.add_argument('--epochs', type=int, default=50, help='训练轮数 (默认:50)')
parser.add_argument('--batch', type=int, default=16, help='批次大小 (默认:16)')
parser.add_argument('--imgsz', type=int, default=640, help='输入图像尺寸')
parser.add_argument('--split', type=float, default=0.8, help='训练集比例 (默认:0.8)')
parser.add_argument('--classes', type=str, default=None,
                    help='类别名称，逗号分隔 (如: angry,happy,sad)')
parser.add_argument('--output', type=str, default=None,
                    help='模型输出目录 (默认: 数据集目录/yolo_output)')
parser.add_argument('--weights', type=str, default='yolov8n.pt',
                    help='YOLOv8 权重文件 (默认: yolov8n.pt，自动在脚本目录/缓存目录查找)')

args = parser.parse_args()

# 切换工作目录到脚本所在目录（确保可写）
script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)
print(f"[INFO] 工作目录: {os.getcwd()}", flush=True)

dataset_path = os.path.abspath(args.dataset)

print(f"=" * 55, flush=True)
print(f"[INFO] 数据集路径: {dataset_path}", flush=True)

if not os.path.exists(dataset_path):
    print(f"[ERROR] 数据集路径不存在: {dataset_path}", flush=True)
    sys.exit(1)

# ================= 类别名称处理 =================
DEFAULT_CLASSES = ["angry", "disgust", "fear", "happy", "sad", "surprise", "neutral"]
class_names = DEFAULT_CLASSES
if args.classes:
    class_names = [c.strip() for c in args.classes.split(",") if c.strip()]

print(f"[INFO] 类别定义 ({len(class_names)}类): {class_names}", flush=True)

# ================= 输出目录 =================
output_base = args.output if args.output else os.path.join(dataset_path, "yolo_output")
output_base = os.path.abspath(output_base)

# ================= 检测数据集结构 =================
# 判断是否已经是YOLO标准结构 (有 images/labels 子目录)
is_yolo_structure = (
    os.path.exists(os.path.join(dataset_path, "images")) and
    os.path.exists(os.path.join(dataset_path, "labels"))
)

if is_yolo_structure:
    print(f"[INFO] 检测到 YOLO 标准目录结构，直接使用", flush=True)
    yolo_data_dir = dataset_path
else:
    # 扁平目录：需要自动划分
    print(f"[INFO] 检测到扁平目录结构，正在自动划分...", flush=True)
    
    yolo_data_dir = os.path.join(output_base, "yolo_dataset")
    
    if os.path.exists(yolo_data_dir):
        shutil.rmtree(yolo_data_dir)
    
    for sub in ["images/train", "images/val", "labels/train", "labels/val"]:
        os.makedirs(os.path.join(yolo_data_dir, sub), exist_ok=True)
    
    # 支持多种图片格式
    image_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp')
    images = [f for f in os.listdir(dataset_path)
              if f.lower().endswith(image_extensions) and not f.startswith('.')]
    
    if not images:
        print(f"[ERROR] 数据集中没有找到图片文件！", flush=True)
        sys.exit(1)
    
    random.seed(42)
    random.shuffle(images)
    
    split_idx = max(1, int(len(images) * args.split))
    train_imgs = images[:split_idx]
    val_imgs = images[split_idx:]
    
    def copy_files(img_list, mode):
        """复制图片及其对应的标签文件"""
        count = 0
        for img in img_list:
            base_name = os.path.splitext(img)[0]
            label_file = base_name + ".txt"
            
            shutil.copy2(
                os.path.join(dataset_path, img),
                os.path.join(yolo_data_dir, "images", mode, img)
            )
            
            src_label = os.path.join(dataset_path, label_file)
            if os.path.exists(src_label):
                shutil.copy2(
                    src_label,
                    os.path.join(yolo_data_dir, "labels", mode, label_file)
                )
                count += 1
        
        return count
    
    train_labels = copy_files(train_imgs, "train")
    val_labels = copy_files(val_imgs, "val")
    
    print(f"[INFO] 划分完成 -> 训练:{len(train_imgs)}张({train_labels}标签) | 验证:{len(val_imgs)}张({val_labels}标签)", flush=True)

# ================= 生成 data.yaml =================
yaml_path = os.path.join(yolo_data_dir, "data.yaml")

yaml_content = f"""# Auto-generated by train.py - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
path: {yolo_data_dir}
train: images/train
val: images/val

nc: {len(class_names)}
names:
"""
for i, name in enumerate(class_names):
    yaml_content += f"  {i}: {name}\n"

with open(yaml_path, "w", encoding="utf-8") as f:
    f.write(yaml_content)

print(f"[INFO] data.yaml -> {yaml_path}", flush=True)

# ================= YOLOv8 训练 =================
model_output_dir = os.path.join(output_base, "runs")

print(f"\n{'='*55}", flush=True)
print(f"[TRAIN] 开始 YOLOv8 训练...", flush=True)
print(f"  配置文件: {yaml_path}", flush=True)
print(f"  Epochs:   {args.epochs}", flush=True)
print(f"  Batch:    {args.batch}", flush=True)
print(f"  ImgSize:  {args.imgsz}", flush=True)
print(f"  输出目录: {model_output_dir}", flush=True)
print(f"{'='*55}\n", flush=True)

start_time = time.time()
best_model_path = ""
last_model_path = ""

# ================= 权重文件查找 =================
def find_weights(name):
    candidates = [
        name,
        os.path.join(script_dir, name),
        os.path.expanduser(f"~/.config/ultralytics/{name}"),
        os.path.join(os.getcwd(), name),
    ]
    for p in candidates:
        if os.path.isfile(p):
            return os.path.abspath(p)
    return None

weights_path = find_weights(args.weights)
if weights_path is None:
    print(f"[ERROR] ❌ 权重文件未找到: {args.weights}", flush=True)
    print(f"[INFO] 请手动下载 {args.weights} 并放置到以下任一位置：", flush=True)
    print(f"        1. 脚本目录: {script_dir}/", flush=True)
    print(f"        2. 当前目录: {os.getcwd()}/", flush=True)
    print(f"        3. 缓存目录: ~/.config/ultralytics/", flush=True)
    print(f"[INFO] 下载地址 (需翻墙):", flush=True)
    print(f"        https://github.com/ultralytics/assets/releases/download/v8.4.0/{args.weights}", flush=True)
    print(f"[INFO] 或使用 --weights 参数指定本地文件路径", flush=True)
    sys.exit(1)

print(f"[INFO] 权重文件: {weights_path}", flush=True)

try:
    model = YOLO(weights_path)
    
    results = model.train(
        data=yaml_path,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        verbose=True,
        project=model_output_dir,     # 固定输出到指定目录
        name="train",                 # 统一命名为train
        exist_ok=True,                # 覆盖已有
        save=True,
        plots=True
    )
    
    elapsed = time.time() - start_time
    minutes = int(elapsed // 60)
    seconds = int(elapsed % 60)
    
    # 确定最终模型路径
    best_model_path = os.path.join(model_output_dir, "train", "weights", "best.pt")
    last_model_path = os.path.join(model_output_dir, "train", "weights", "last.pt")
    
    print(f"\n{'='*55}", flush=True)
    print(f"[DONE] ✅ 训练完成！", flush=True)
    print(f"  总耗时: {minutes}分{seconds}秒", flush=True)
    
    if results and hasattr(results, 'results_dict'):
        rd = results.results_dict
        map50 = rd.get('metrics/mAP50(B)', 'N/A')
        map5095 = rd.get('metrics/mAP50-95(B)', 'N/A')
        print(f"  mAP50:     {map50}", flush=True)
        print(f"  mAP50-95:  {map5095}", flush=True)
        # 结构化输出，方便 C++ 端解析
        print(f"[METRICS] mAP50={map50} mAP50-95={map5095}", flush=True)
    
    print(f"\n  📦 最佳模型: {best_model_path}", flush=True)
    print(f"  📦 最新模型: {last_model_path}", flush=True)
    
    if os.path.exists(best_model_path):
        size_mb = os.path.getsize(best_model_path) / (1024 * 1024)
        print(f"  📊 模型大小: {size_mb:.1f} MB", flush=True)
    
    print(f"{'='*55}", flush=True)
    
except Exception as e:
    print(f"\n[ERROR] ❌ 训练异常: {str(e)}", flush=True)
    import traceback
    traceback.print_exc()
    sys.exit(1)
